rtc_params:
  min_ip: 200
  max_ip: 254

phones:
  Chaos: &Chaos
    name: Chaos
    manufacturer:
    model:
    vendor: Apple
    family: iOS
    version: '6'
    platform: ios
    release_type: PU1
    ip: 192.168.5.200
    udid: e3f43g3
    user: rtc-Chaos@cobi.bike
    deployment_path:
      hub: tp_link_tlsg3424
      port: port12
  Nyx: &Nyx
    name: Nyx
    manufacturer:
    model:
    vendor: Samsung
    family: ST
    version: '43'
    platform: android
    release_type: PU100
    ip: 192.168.5.201
    udid: g433
    user: rtc-Nyx@cobi.bike
    deployment_path:
      hub: tp_link_tlsg3424
      port: port13

  Erebos:
    name: Erebos
    manufacturer:
    model:
    vendor: Apple
    family: iOS
    version: '4'
    platform: ios
    release_type: PU1
    ip: 192.168.5.202
    udid: rg343
    user: rtc-Erebos@cobi.bike
    deployment_path:
      hub:
      port:
  Hesperiden:
    name: Hesperiden
    manufacturer:
    model:
    vendor: Apple
    family: iOS
    version: '23'
    platform: ios
    release_type: PU100
    ip: 192.168.5.203
    udid: g4h34h
    user: rtc-Hesperiden@cobi.bike
    deployment_path:
      hub:
      port:
  Aither:
    name: Aither
    manufacturer:
    model:
    vendor: Apple
    family: nOS
    version: '3'
    platform: ios
    release_type: PU1
    ip: 192.168.5.204
    udid: f43g43
    user: rtc-Aither@cobi.bike
    deployment_path:
      hub:
      port:
biab:
  ariel: &ariel
    name: Ariel
    bbp: 'false'
    bdu: 'false'
  carme: &carme
    name: Carme
    bbp: 'false'
    bdu: 'false'
  deimos: &deimos
    name: Deimos
    bbp: 'false'
    bdu: 'false'
  despina: &despina
    name: Despina
    bbp: 'false'
    bdu: 'false'
  helike: &helike
    name: Helike
    bbp: 'false'
    bdu: 'false'
  phobos: &phobos
    name: Phobos
    bbp: 'false'
    bdu: 'false'
  proteus: &proteus
    name: Proteus
    #bbp: 'false'
    #bdu: 'false'
  valetudo: &valetudo
    name: Valetudo
    bbp: 'false'
    bdu: 'false'

bts:
  bts_black_mask: &bts_black_mask
    name: bts-black-mask
    ip: 192.168.5.138
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08004-0117-01-A10-00-0000
    biab: *phobos
    ebike_release_set: ''
  bts_black_flash: &bts_black_flash
    name: bts-black-flash
    ip: 192.168.5.136
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08004-0038-01-A10-00-0000
    biab: *deimos
    ebike_release_set: ''
  bts_batwoman: &bts_batwoman
    name: bts-batwoman
    ip: 192.168.5.137
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08004-0170-01-A10-00-0000
    biab: *valetudo
    ebike_release_set: ''
  bts_atom_smasher: &bts_atom_smasher
    name: bts-atom-smasher
    ip: 192.168.5.135
    brc:
      hw_revision: '4.0'
      mac_address: ''
      serial_number: 07614-0160-01-A10-00-0000
    ebike_release_set: ''
  bts_aurora: &bts_aurora
    name: bts-aurora
    ip: 192.168.5.134
    brc:
      hw_revision: '4.0'
      mac_address: ''
      serial_number: 07614-0029-01-A10-00-0000
    ebike_release_set: ''
  bts_azazel: &bts_azazel
    name: bts-azazel
    ip: 192.168.5.133
    brc:
      hw_revision: '4.0'
      mac_address: ''
      serial_number: 07614-0164-01-A10-00-0000
    ebike_release_set: ''
  bts_bishop: &bts_bishop
    name: bts-bishop
    ip: 192.168.5.139
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08004-0171-01-A10-00-0000
    biab: *carme
    ebike_release_set: ''
  bts_black_bolt: &bts_black_bolt
    name: bts-black-bolt
    ip: 192.168.5.140
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08004-0145-01-A10-00-0000
    biab: *helike
    ebike_release_set: ''
  bts_black_adam: &bts_black_adam
    name: bts-black-adam
    ip: 192.168.5.142
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08004-0169-01-A10-00-0000
    biab: *proteus
    ebike_release_set: ''
  bts_beast_boy: &bts_beast_boy
    name: bts-beast-boy
    ip: 192.168.5.141
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 08005-0017-01-A10-00-0000
    biab: *ariel
    ebike_release_set: ''
  bts_black_condor: &bts_black_condor
    name: bts-black-condor
    ip: 192.168.5.143
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 14013-0037-01-A10-00-0000
    biab: *despina

# list of access points
# provide wifi
access_point:
  ubiquiti_uap_nanohd: &ubiquiti_uap_nanohd
    name: Ubiquiti UAP-nanoHD

# list of ethernet switches
# provide LAN connectivity
# binding to BTS and hence to biab
switch:
  tp_link_tlsg3424: &tp_link_tlsg3424
    name: TP-Link TLSG3424
    port01: *bts_black_mask
    port02: *bts_black_flash
    port03: *bts_batwoman
    port04: *bts_atom_smasher
    port05: *bts_aurora
    port06: *bts_azazel
    port07: *bts_bishop
    port08: *bts_black_bolt
    port09: *bts_black_adam
    port10: *bts_beast_boy
    port11: *bts_black_condor
    port12: *Chaos
    port13: *Nyx
    port14:
    port15:
    port16:
    port17:
    port18:
    port19:
    port20:
    port21:
    port22:
    port23:
    port24: *ubiquiti_uap_nanohd

usb_hub:
  exsys_ex_1116hmvs_1: &exsys_ex_1116hmvs_1
    name: ExSys EX-1116HMVS
    port01:
    port02:
    port03:
    port04:
    port05:
    port06:
    port07:
    port08:

  exsys_ex_1116hmvs_2: &exsys_ex_1116hmvs_2
    name: ExSys EX-1116HMVS
    port01:
    port02:
    port03:
    port04:
    port05:
    port06:
    port07:
    port08:
    port09:
    port10:
    port11:
    port12:
    port13:
    port14:
    port15:
    port16:

stages:
  prod:
  - *tp_link_tlsg3424
  dev:
  - *exsys_ex_1116hmvs_1
  - *exsys_ex_1116hmvs_2
