[pytest]
markers =
    add_a_new_phone: mark as 
    change_existing_phone: mark as 
    deploy_phone: mark as 
    undeploy_phone: mark as 
    remove_phone: mark as 
    show_phone_configuration: mark as 
    display: mark as 
