---
# conventions:
# allowed characters for keys and anchor [a-b09_]

rtc_params:
  min_ip: 220
  max_ip: 254


# list of biabs
# names https://de.wikipedia.org/wiki/Liste_der_Monde_von_Planeten_und_Zwergplaneten
biab:
  ariel: &ariel
    name: Ariel
    bbp: 'false'
    bdu: 'false'
  carme: &carme
    name: Carme
    bbp: 'false'
    bdu: 'false'
  deimos: &deimos
    name: Deimos
    bbp: 'false'
    bdu: 'false'
  despina: &despina
    name: Despina
    bbp: 'false'
    bdu: 'false'
  helike: &helike
    name: Helike
    bbp: 'false'
    bdu: 'false'
  phobos: &phobos
    name: Phobos
    bbp: 'false'
    bdu: 'false'
  proteus: &proteus
    name: Proteus
    #bbp: 'false'
    #bdu: 'false'
  valetudo: &valetudo
    name: Valetudo
    bbp: 'false'
    bdu: 'false'

# list of bts
# name given by https://mac-address-manager.ebike.dev/ during bts setup
bts:
  bts_black_mask: &bts_black_mask
    name: bts-black-mask
    ip: 192.168.5.138
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08004-0117-01-A10-00-0000'
    biab: *phobos
    ebike_release_set: ''
  bts_black_flash: &bts_black_flash
    name: bts-black-flash
    ip: 192.168.5.136
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08004-0038-01-A10-00-0000'
    biab: *deimos
    ebike_release_set: ''
  bts_batwoman: &bts_batwoman
    name: bts-batwoman
    ip: 192.168.5.137
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08004-0170-01-A10-00-0000'
    biab: *valetudo
    ebike_release_set: ''
  bts_atom_smasher: &bts_atom_smasher
    name: bts-atom-smasher
    ip: 192.168.5.135
    brc:
      hw_revision: '4.0'
      mac_address: ''
      serial_number: 07614-0160-01-A10-00-0000
    ebike_release_set: ''
  bts_aurora: &bts_aurora
    name: bts-aurora
    ip: 192.168.5.134
    brc:
      hw_revision: '4.0'
      mac_address: ''
      serial_number: 07614-0029-01-A10-00-0000
    ebike_release_set: ''
  bts_azazel: &bts_azazel
    name: bts-azazel
    ip: 192.168.5.133
    brc:
      hw_revision: '4.0'
      mac_address: ''
      serial_number: 07614-0164-01-A10-00-0000
    ebike_release_set: ''
  bts_bishop: &bts_bishop
    name: bts-bishop
    ip: 192.168.5.139
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08004-0171-01-A10-00-0000'
    biab: *carme
    ebike_release_set: ''
  bts_black_bolt: &bts_black_bolt
    name: bts-black-bolt
    ip: 192.168.5.140
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08004-0145-01-A10-00-0000'
    biab: *helike
    ebike_release_set: ''
  bts_black_adam: &bts_black_adam
    name: bts-black-adam
    ip: 192.168.5.142
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08004-0169-01-A10-00-0000'
    biab: *proteus
    ebike_release_set: ''
  bts_beast_boy: &bts_beast_boy
    name: bts-beast-boy
    ip: 192.168.5.141
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: '08005-0017-01-A10-00-0000'
    biab: *ariel
    ebike_release_set: ''
  bts_black_condor: &bts_black_condor
    name: bts-black-condor
    ip: 192.168.5.143
    brc:
      hw_revision: '5.0'
      mac_address: ''
      serial_number: 14013-0037-01-A10-00-0000
    biab: *despina

# list of phones
# all phones available for test
# phones connected to an usb hub is deployed
# phones without are not deployed
# phone names https://de.wikipedia.org/wiki/Griechische_Mythologie
phones:
  zeus: &zeus
    name: Zeus
    manufacturer: Apple
    model: iPhone 7
    platform: ios
    release_type: PU1
    ip: 192.168.5.248
    udid: 004dbf2d1352472f9c40c6cc62da3c5d43ce2672
    user: rtc+PROD_iPhone7@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: 6205
      performance: 6198
  demeter: &demeter
    name: Demeter
    manufacturer: Apple
    model: iPhone 11
    platform: ios
    release_type: PU1
    ip: 192.168.5.253
    udid: "00008030-000A384A1A79802E"
    user: rtc+PROD_iPhone11@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: 6194
      functional: 6204
      performance: 6197
  hades: &hades
    name: Hades
    manufacturer: Apple
    model: iPhone SE
    platform: ios
    release_type: PU1
    ip: 192.168.5.252
    udid: 00008030-000C29023ED0402E
    user: rtc+PROD_iPhoneSE@cobi.bike
    testrun_ids:
      fota: 6211
      activitytracking: ''
      functional: 6206
      performance: 6199
  hera: &hera
    name: Hera
    manufacturer: Apple
    model: iPhone 12
    platform: ios
    release_type: PU100
    ip: 192.168.5.242
    udid: 00008101-001479342EF8001E
    user: rtc+PROD_iPhone12@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  hestia: &hestia
    name: Hestia
    manufacturer: Huawei
    model: P30 Lite
    platform: android
    release_type: PU1
    ip: 192.168.5.251
    udid: 22X0220526002341
    user: rtc+PROD_HuaweiP30@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: 6193
      functional: 6203
      performance: 6196
  poseidon: &poseidon
    name: Poseidon
    manufacturer: Samsung
    model: Galaxy S10
    platform: android
    release_type: PU1
    ip: 192.168.5.250
    udid: RF8KC29SFFY
    user: rtc+PROD_SamsungS10@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: 6207
      performance: 6200
  ares: &ares
    name: Ares
    manufacturer: Samsung
    model: Galaxy S8
    platform: android
    release_type: PU1
    ip: 192.168.5.249
    udid: ce12171ca011901203
    user: rtc+PROD_SamsungS8@cobi.bike
    testrun_ids:
      fota: 6210
      activitytracking: ''
      functional: 6208
      performance: 6201
  hephaistos: &hephaistos
    name: Hephaistos
    manufacturer: Nokia
    model: '3.4'
    platform: android
    release_type: PU100
    ip: 192.168.5.239
    udid: HZQL1838HAL10502562
    user: rtc+PROD_Nokia3.4@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  hebe: &hebe
    name: Hebe
    manufacturer: Xiaomi
    model: Mi Note 10
    platform: android
    release_type: PU100
    ip: 192.168.5.245
    udid: 4ee2234c
    user: rtc+PROD_MiNote10@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  eileithyia: &eileithyia
    name: Eileithyia
    manufacturer: Xiaomi
    model: Poco X3
    platform: android
    release_type: PU100
    ip: 192.168.5.247
    udid: f01f9080
    user: rtc+PROD_POCOX3@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  artemis: &artemis
    name: Artemis
    manufacturer: Samsung
    model: Galaxy A5
    platform: android
    release_type: PU100
    ip: 192.168.5.243
    udid: 52100b50b4ed8449
    user: rtc+PROD_SamsungA5@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  apollon: &apollon
    name: Apollon
    manufacturer: Google
    model: Pixel 4a
    platform: android
    release_type: PU100
    ip: 192.168.5.244
    udid: 13181JEC205962
    user: rtc+PROD_GooglePixel4a@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  hermes: &hermes
    name: Hermes
    manufacturer: Motorola
    model: Moto G9 Play
    platform: android
    release_type: PU100
    ip: 192.168.5.241
    udid: ZY32BQH75B
    user: rtc+PROD_MotoG9_Play@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  athene: &athene
    name: Athene
    manufacturer: Motorola
    model: Moto G9 Play
    platform: android
    release_type: PU100
    ip: 192.168.5.226
    udid: ZY32BQH8BH
    user: rtc+DEV_MotoG9_Play@cobi.bike
  persephone: &persephone
    name: Persephone
    manufacturer: Apple
    model: iPhone 7
    platform: ios
    release_type: PU1
    ip: 192.168.5.220
    udid: 346f88b4f630560afd9f38a6f4a6546fe279835f
    user: rtc+DEV_iPhone7@cobi.bike
  herakles: &herakles
    name: Herakles
    manufacturer: Xiaomi
    model: Poco X3
    platform: android
    release_type: PU100
    ip: 192.168.5.233
    udid: 3facff51
    user: rtc+DEV_POCOX3@cobi.bike
  dionysos: &dionysos
    name: Dionysos
    manufacturer: Apple
    model: iPhone SE2
    platform: ios
    release_type: PU100
    ip: 192.168.5.230
    udid:
    user:
  acheloos: &acheloos
    name: Acheloos
    manufacturer: Huawei
    model: P30
    platform: android
    release_type: PU1
    ip: 192.168.5.223
    udid: XPH0220825001314
    user: rtc+DEV_HuaweiP30@cobi.bike
  aletheia: &aletheia
    name: Aletheia
    manufacturer: Apple
    model: iPhone SE
    platform: ios
    release_type: PU1
    ip: 192.168.5.222
    udid: 00008030-001E6C10210B802E
    user: rtc+DEV_iPhoneSE@cobi.bike
  anemoi: &anemoi
    name: Anemoi
    manufacturer: Samsung
    model: Galaxy S8
    platform: android
    release_type: PU1
    ip: 192.168.5.225
    udid: ce01182114acb50d03
  asklepios: &asklepios
    name: Asklepios
    manufacturer: Apple
    model: iPhone 12
    platform: ios
    release_type: PU100
    ip: 192.168.5.229
    udid: 00008101-001315A00E08001E
    user: rtc+DEV_iPhone12@cobi.bike
  ate: &ate
    name: Ate
    manufacturer: Apple
    model: iPhone 11
    platform: ios
    release_type: PU100
    ip: 192.168.5.231
    udid: 00008030-001D709A0A46402E
    user: rtc+DEV_iPhone11@cobi.bike
  charon: &charon
    name: Charon
    manufacturer: Xiaomi
    model: Mi Note 10
    platform: android
    release_type: PU100
    ip: 192.168.5.232
    udid: fecbd761
    user: rtc+DEV_MiNote10@cobi.bike
  hekate: &hekate
    name: Hekate
    manufacturer: Samsung
    model: Galaxy A41
    platform: android
    release_type: PU100
    ip: 192.168.5.227
    udid: R58R124AM4K
    user: rtc+DEV1_SamsungA41@cobi.bike
  hesperiden: &hesperiden
    name: Hesperiden
    manufacturer: Samsung
    model: Galaxy S10
    platform: android
    release_type: PU1
    ip: 192.168.5.224
    udid: RF8M418VE4R
    user: rtc+DEV_SamsungS10@cobi.bike
  horen: &horen
    name: Horen
    manufacturer: Nokia
    model: '3.4'
    platform: android
    release_type: PU100
    ip: 192.168.5.246
    udid: HZQL1838HAL10502197
    user: rtc+DEV_Nokia3.4@cobi.bike
  hymenaios: &hymenaios
    name: Hymenaios
    manufacturer: Samsung
    model: Galaxy A5
    platform: android
    release_type: PU100
    ip: 192.168.5.247
    udid: 5210a9b2b449b4c5
    user: rtc+DEV_SamsungA5@cobi.bike
  hypnos: &hypnos
    name: Hypnos
    manufacturer: Apple
    model: iPhone X
    platform: ios
    release_type: PU100
    ip: 192.168.5.235
    udid: bb2cae5df8cf95b51318b0892e2f01b3d71336bb
    user: rtc+Dev_iPhoneX@cobi.bike
  iris: &iris
    name: Iris
    manufacturer: Apple
    model: iPhone 8
    platform: ios
    release_type: PU100
    ip: 192.168.5.238
    udid: 058af93ad8c44cd457671fa27f5ce2b70ef4fe2f
    user: rtc+DEV_iPhone8@cobi.bike
  zephyros: &zephyros
    name: Zephyros
    manufacturer: Google
    model: Pixel 4a
    platform: android
    release_type: PU100
    ip: 192.168.5.236
    udid: 14141JEC206484
    user: rtc+DEV_GooglePixel4a@cobi.bike
  moiren: &moiren
    name: Moiren
    manufacturer: Apple
    model: iPhone 8
    platform: ios
    release_type: PU100
    ip: 192.168.5.254
    udid:
    user: rtc+PROD_iPhone8@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: '6446'
  morpheus: &morpheus
    name: Morpheus
    manufacturer: Apple
    model: iPhone X
    platform: ios
    release_type: PU100
    ip: 192.168.5.237
    udid: 98a77d0688f6c4d4314887ae9fabc252202b42df
    user: rtc+PROD_iPhoneX@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: ''
      functional: ''
      performance: ''
  musen: &musen
    name: Musen
    manufacturer: Samsung
    model: Galaxy A41
    platform: android
    release_type: PU100
    ip: 192.168.5.240
    udid: R58R1260KSE
    user: rtc+PROD_SamsungA41@cobi.bike
    testrun_ids:
      fota: ''
      activitytracking: '6481'
      functional: ''
      performance: '6452'

# list of usb hubs
# connections to phones
# connection means also phone is deployed / available for testing
usb_hub:
  exsys_ex_1116hmvs_1: &exsys_ex_1116hmvs_1
    name: ExSys EX-1116HMVS
    port01: *zeus
    port02: *demeter
    port03: *hades
    port04: *hera
    port05: *hestia
    port06: *poseidon
    port07: *ares
    port08: *hephaistos
    port09: *hebe
    port10: *eileithyia
    port11: *artemis
    port12: *apollon
    port13: *hermes
    port14: *morpheus
    port15: *musen
    port16:
  exsys_ex_1116hmvs_2: &exsys_ex_1116hmvs_2
    name: ExSys EX-1116HMVS
    port01: *athene
    port02: *persephone
    port03: *herakles
    port04: *zephyros
    port05: *acheloos
    port06: *aletheia
    port07: *anemoi
    port08: *asklepios
    port09: *ate
    port10: *charon
    port11: *hekate
    port12: *hesperiden
    port13: *horen
    port14: *hymenaios
    port15: *hypnos
    port16: *iris

# list of mac minis
# binding to usb hub and hence to phones
macmini:
  ironman: &ironman
    name: Ironman
    ip: 192.168.5.21
    hubs:
      hub1: *exsys_ex_1116hmvs_1
  elektra: &elektra
    name: Elektra
    ip: 192.168.5.25
    hubs:
      hub1: *exsys_ex_1116hmvs_2

# list of access points
# provide wifi
access_point:
  ubiquiti_uap_nanohd: &ubiquiti_uap_nanohd
    name: Ubiquiti UAP-nanoHD

# list of ethernet switches
# provide LAN connectivity
# binding to BTS and hence to biab
switch:
  tp_link_tlsg3424: &tp_link_tlsg3424
    name: TP-Link TLSG3424
    port01: *bts_black_mask
    port02: *bts_black_flash
    port03: *bts_batwoman
    port04: *bts_atom_smasher
    port05: *bts_aurora
    port06: *bts_azazel
    port07: *bts_bishop
    port08: *bts_black_bolt
    port09: *bts_black_adam
    port10: *bts_beast_boy
    port11: *bts_black_condor
    port12: *elektra
    port13: *ironman
    port14:
    port15:
    port16:
    port17:
    port18:
    port19:
    port20:
    port21:
    port22:
    port23:
    port24: *ubiquiti_uap_nanohd

# list of stages
# defines the stage typ of all devices
# following reverse
stages:
  rtc:
    - <<: *tp_link_tlsg3424
  test_stages:
    prod1:
      # mac mini at first pos
      - <<: *ironman
      - <<: *bts_black_mask
      - <<: *bts_black_flash
      - <<: *bts_bishop
      - <<: *bts_black_bolt
      - <<: *bts_black_adam
      - <<: *bts_beast_boy
      - <<: *bts_black_condor
    dev1:
      # mac mini at first pos
      - <<: *elektra
      - <<: *bts_batwoman
      - <<: *bts_atom_smasher
      - <<: *bts_aurora
      - <<: *bts_azazel